services:
  backend:
    build:
      target: dev
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
  frontend:
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/share/nginx/html
